# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4915bda3afd2292c58f245c477d07b6faa1320558d147faa632bfc0a6698f6b9fbdcbad2ab273979c6b277c0cbc1beac52a16853cf474921bfe3b6d2cbabce5d

test:
  secret_key_base: 73ddf18e23b6983a7e7bf1b678f478a08d67945a132ea62d043dc00333448d891a95e54186bb5a22f9e253f362ddc583c1e14ae029b252dfb2e9a3843cd1b118

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
